# Generated by Django 2.0.2 on 2021-12-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('industry', models.CharField(choices=[('Transport', 'Transport'), ('Pharma', 'Pharma'), ('Entertainment', 'Entertainment'), ('Mining', 'Mining'), ('IT', 'IT'), ('Food', 'Food'), ('Healthcare', 'Healthcare'), ('Farming', 'Farming'), ('Retail', 'Retail'), ('Government', 'Government'), ('Sport', 'Sport'), ('Media', 'Media'), ('Music', 'Music'), ('Construction', 'Construction'), ('Hospitality', 'Hospitality'), ('Agriculture', 'Agriculture'), ('Electronics', 'Electronics'), ('Education', 'Education'), ('Energy', 'Energy'), ('Telecoms', 'Telecoms'), ('Manufacturing', 'Manufacturing')], default='Government', max_length=20)),
                ('location', models.CharField(choices=[('Antrim', 'Antrim'), ('Armagh', 'Armagh'), ('Carlow', 'Carlow'), ('Cavan', 'Cavan'), ('Clare', 'Clare'), ('Cork', 'Cork'), ('Derry', 'Derry'), ('Donegal', 'Donegal'), ('Down', 'Down'), ('Dublin', 'Dublin'), ('Fermanagh', 'Fermanagh'), ('Galway', 'Galway'), ('Kerry', 'Kerry'), ('Kildare', 'Kildare'), ('Kilkenny', 'Kilkenny'), ('Laois', 'Laois'), ('Leitrim', 'Leitrim'), ('Limerick', 'Limerick'), ('Longford', 'Longford'), ('Louth', 'Louth'), ('Mayo', 'Mayo'), ('Meath', 'Meath'), ('Monaghan', 'Monaghan'), ('Offaly', 'Offaly'), ('Roscommon', 'Roscommon'), ('Sligo', 'Sligo'), ('Tipperary', 'Tipperary'), ('Tyrone', 'Tyrone'), ('Waterford', 'Waterford'), ('Westmeath', 'Westmeath'), ('Wexford', 'Wexford'), ('Wicklow', 'Wicklow')], default='Antrim', max_length=15)),
            ],
        ),
    ]
